# SPDX-FileCopyrightText: Copyright (c) 2019 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/MethodLength:
  Max: 50
Layout/ParameterAlignment:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
require: []
