AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  NewCops: enable

Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/MethodLength:
  Max: 50
Layout/ParameterAlignment:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
